import '../../data/models/exam_subject.dart';

class ExamSubjectsData {
  ExamSubjectsData._();

  static final List<ExamSubject> allSubjects = [
    // 核心考科
    ExamSubject(
      id: 'cisco-200-301',
      code: '200-301',
      title: 'Cisco Certified Network Associate (CCNA)',
      category: 'Associate',
      description: '涵蓋網路基礎、網路存取、IP 連線能力、IP 服務、資安基礎與自動化/可程式化性。',
      totalQuestions: 800,
      domains: [
        '1.0 網路基礎 (Network Fundamentals)',
        '2.0 網路存取 (Network Access)',
        '3.0 IP 連線能力 (IP Connectivity)',
        '4.0 IP 服務 (IP Services)',
        '5.0 資安基礎 (Security Fundamentals)',
        '6.0 自動化與可程式化性 (Automation and Programmability)',
      ],
      iconName: 'router',
      isPopular: true,
    ),

    // Enterprise 領域
    ExamSubject(
      id: 'cisco-350-401',
      code: '350-401',
      title: 'Implementing Cisco Enterprise Network Core Technologies (ENCOR)',
      category: 'Professional / Core',
      description: 'CCNP Enterprise 與 CCIE Enterprise 核心考科：架構、虛擬化、基礎設施、網路保障、安全與自動化。',
      totalQuestions: 650,
      domains: [
        '1.0 架構 (Architecture)',
        '2.0 虛擬化 (Virtualization)',
        '3.0 基礎設施 (Infrastructure)',
        '4.0 網路保障 (Network Assurance)',
        '5.0 安全 (Security)',
        '6.0 自動化 (Automation)',
      ],
      iconName: 'hub',
      isPopular: true,
    ),
    ExamSubject(
      id: 'cisco-300-410',
      code: '300-410',
      title: 'Implementing Cisco Enterprise Advanced Routing and Services (ENARSI)',
      category: 'Professional / Concentration',
      description: '進階第 3 層路由技術、VPN 服務、基礎架構安全與基礎架構服務故障排除。',
      totalQuestions: 500,
      domains: [
        '1.0 第 3 層技術 (Layer 3 Technologies)',
        '2.0 VPN 服務 (VPN Services)',
        '3.0 基礎設施安全 (Infrastructure Security)',
        '4.0 基礎設施服務 (Infrastructure Services)',
      ],
      iconName: 'alt_route',
      isPopular: true,
    ),
    ExamSubject(
      id: 'cisco-300-415',
      code: '300-415',
      title: 'Implementing Cisco SD-WAN Solutions (ENSDWI)',
      category: 'Professional / Concentration',
      description: 'Cisco SD-WAN 架構、控制器部署、廣域網邊界路由器部署、策略與安全性實作。',
      totalQuestions: 400,
      domains: [
        '1.0 SD-WAN 架構 (Architecture)',
        '2.0 控制器部署 (Controller Deployment)',
        '3.0 路由器部署 (Router Deployment)',
        '4.0 策略 (Policies)',
        '5.0 安全與服務品質 (Security and QoS)',
      ],
      iconName: 'cloud_sync',
    ),
    ExamSubject(
      id: 'cisco-300-420',
      code: '300-420',
      title: 'Designing Cisco Enterprise Networks (ENSLD)',
      category: 'Professional / Concentration',
      description: '進階企業網路設計：進階定址與路由方案、企業園區網路、進階 WAN 與 SDA 設計。',
      totalQuestions: 350,
      domains: [
        '1.0 進階定址與路由 (Advanced Addressing and Routing)',
        '2.0 進階企業園區網路 (Advanced Enterprise Campus Networks)',
        '3.0 WAN 網路設計 (WAN for Enterprise Networks)',
        '4.0 網路服務設計 (Network Services)',
      ],
      iconName: 'design_services',
    ),
    ExamSubject(
      id: 'cisco-300-425',
      code: '300-425',
      title: 'Designing Cisco Enterprise Wireless Networks (ENWLSD)',
      category: 'Professional / Concentration',
      description: '無線網路站點評估、無線網路設計、移動性與高可用性架構。',
      totalQuestions: 300,
      domains: [
        '1.0 無線站點調查 (Wireless Site Survey)',
        '2.0 有線與無線基礎設施 (Wired and Wireless Infrastructure)',
        '3.0 移動性 (Mobility)',
        '4.0 高可用性 (High Availability)',
      ],
      iconName: 'wifi',
    ),
    ExamSubject(
      id: 'cisco-300-430',
      code: '300-430',
      title: 'Implementing Cisco Enterprise Wireless Networks (ENWLSI)',
      category: 'Professional / Concentration',
      description: '無線客戶端連線實作、多播服務、位置服務與進階安全排錯。',
      totalQuestions: 320,
      domains: [
        '1.0 FlexConnect 實作',
        '2.0 服務品質 (QoS)',
        '3.0 多播 (Multicast)',
        '4.0 位置服務 (Location Services)',
        '5.0 安全與設備管理 (Security and Device Management)',
      ],
      iconName: 'settings_input_antenna',
    ),
    ExamSubject(
      id: 'cisco-300-435',
      code: '300-435',
      title: 'Automating Cisco Enterprise Solutions (ENAUTO)',
      category: 'Professional / Concentration',
      description: '網路程式化、DNA Center API、SD-WAN API、Meraki API 與 Python 自動化腳本開發。',
      totalQuestions: 380,
      domains: [
        '1.0 網路可程式化基礎 (Network Programmability Foundation)',
        '2.0 自動化 API (Automate APIs and Protocols)',
        '3.0 Cisco DNA Center 自動化',
        '4.0 Cisco SD-WAN 自動化',
        '5.0 Cisco Meraki 自動化',
      ],
      iconName: 'terminal',
      isPopular: true,
    ),

    // Data Center 領域
    ExamSubject(
      id: 'cisco-350-601',
      code: '350-601',
      title: 'Implementing Cisco Data Center Core Technologies (DCCOR)',
      category: 'Professional / Core',
      description: '資料中心網路、運算基礎設施、儲存網路 (SAN)、自動化與安全性。',
      totalQuestions: 450,
      domains: [
        '1.0 資料中心網路 (Network)',
        '2.0 運算 (Compute)',
        '3.0 儲存網路 (Storage Network)',
        '4.0 自動化 (Automation)',
        '5.0 安全 (Security)',
      ],
      iconName: 'dns',
      isPopular: true,
    ),
    ExamSubject(
      id: 'cisco-300-610',
      code: '300-610',
      title: 'Designing Cisco Data Center Infrastructure (DCID)',
      category: 'Professional / Concentration',
      description: '資料中心網路設計、運算節點架構與儲存網路拓撲規劃。',
      totalQuestions: 300,
      domains: [
        '1.0 網路設計 (Network Design)',
        '2.0 運算設計 (Compute Design)',
        '3.0 儲存設計 (Storage Network Design)',
        '4.0 自動化設計 (Automation Design)',
      ],
      iconName: 'account_tree',
    ),
    ExamSubject(
      id: 'cisco-300-615',
      code: '300-615',
      title: 'Troubleshooting Cisco Data Center Infrastructure (DCIT)',
      category: 'Professional / Concentration',
      description: '資料中心 LAN、SAN、UCS 運算節點與 ACI 故障排除實務。',
      totalQuestions: 310,
      domains: [
        '1.0 網路故障排除 (Network Troubleshooting)',
        '2.0 運算平台故障排除 (Compute Platforms)',
        '3.0 儲存網路排除 (Storage Area Networks)',
        '4.0 ACI 架構排除 (ACI Troubleshooting)',
      ],
      iconName: 'build',
    ),
    ExamSubject(
      id: 'cisco-300-620',
      code: '300-620',
      title: 'Implementing Cisco Application Centric Infrastructure (DCACI)',
      category: 'Professional / Concentration',
      description: 'Cisco ACI 拓撲、APIC 控制器、租戶策略、合約與外部網路整合。',
      totalQuestions: 340,
      domains: [
        '1.0 ACI 架構與拓撲 (ACI Fabric Infrastructure)',
        '2.0 ACI 封包轉發 (ACI Packet Forwarding)',
        '3.0 外部網路整合 (External Network Connectivity)',
        '4.0 整合與管理 (Integrations and Management)',
      ],
      iconName: 'developer_board',
    ),

    // Security 領域
    ExamSubject(
      id: 'cisco-350-701',
      code: '350-701',
      title: 'Implementing and Operating Cisco Security Core Technologies (SCOR)',
      category: 'Professional / Core',
      description: '網路安全、雲端安全、內容安全、端點防護、安全網路存取、可見度與強制執行。',
      totalQuestions: 520,
      domains: [
        '1.0 安全概念 (Security Concepts)',
        '2.0 網路安全 (Network Security)',
        '3.0 雲端安全 (Cloud Security)',
        '4.0 內容安全 (Content Security)',
        '5.0 端點防護與控制 (Endpoint Protection and Control)',
        '6.0 安全存取與可見度 (Secure Network Access and Visibility)',
      ],
      iconName: 'security',
      isPopular: true,
    ),
    ExamSubject(
      id: 'cisco-300-710',
      code: '300-710',
      title: 'Securing Networks with Cisco Firepower (SNCF)',
      category: 'Professional / Concentration',
      description: 'Firepower 威脅防禦 (FTD)、存取控制策略、NGIPS、NAT 與 VPN 部署。',
      totalQuestions: 360,
      domains: [
        '1.0 部署 (Deployment)',
        '2.0 配置 (Configuration)',
        '3.0 管理與故障排除 (Management and Troubleshooting)',
      ],
      iconName: 'local_fire_department',
    ),
    ExamSubject(
      id: 'cisco-300-715',
      code: '300-715',
      title: 'Implementing and Configuring Cisco Identity Services Engine (SISE)',
      category: 'Professional / Concentration',
      description: 'Cisco ISE 架構、802.1X 認證、Web 授權、Profiler、Posture 與 TrustSec。',
      totalQuestions: 350,
      domains: [
        '1.0 架構與部署 (Architecture and Deployment)',
        '2.0 身份管理 (Identity Management)',
        '3.0 認證與授權 (Authentication and Authorization)',
        '4.0 TrustSec 與安全策略 (TrustSec and Policies)',
      ],
      iconName: 'badge',
    ),
    ExamSubject(
      id: 'cisco-300-730',
      code: '300-730',
      title: 'Implementing Secure Solutions with Virtual Private Networks (SVPN)',
      category: 'Professional / Concentration',
      description: '站點間 VPN (Site-to-Site)、遠端存取 VPN (Remote Access)、DMVPN 與 FlexVPN 深入實作。',
      totalQuestions: 320,
      domains: [
        '1.0 站點間 VPN (Site-to-Site VPNs)',
        '2.0 遠端存取 VPN (Remote Access VPNs)',
        '3.0 安全管理與除錯 (Troubleshooting)',
      ],
      iconName: 'vpn_lock',
    ),

    // Collaboration & DevNet 核心
    ExamSubject(
      id: 'cisco-350-801',
      code: '350-801',
      title: 'Implementing and Operating Cisco Collaboration Core Technologies (CLCOR)',
      category: 'Professional / Core',
      description: '協同運作架構、CUCM 呼叫控制、SIP 通訊協定、QoS 與 Cisco 視訊終端整合。',
      totalQuestions: 380,
      domains: [
        '1.0 架構與設計 (Architecture and Design)',
        '2.0 協同通訊協定 (Protocols, Codecs, and Endpoints)',
        '3.0 Cisco IOS XE 閘道與媒體資源',
        '4.0 呼叫控制 (Call Control)',
        '5.0 QoS 與監控 (QoS and Collaboration Applications)',
      ],
      iconName: 'phone_in_talk',
    ),
    ExamSubject(
      id: 'cisco-350-901',
      code: '350-901',
      title: 'Developing Applications and Automating Workflows using Cisco Platforms (DEVCOR)',
      category: 'Professional / Core',
      description: '軟體開發與設計、使用 API 進行自動化、基礎設施自動化、網路應用程式安全性與雲端部署。',
      totalQuestions: 420,
      domains: [
        '1.0 軟體開發與設計 (Software Development and Design)',
        '2.0 使用 API (Using APIs)',
        '3.0 Cisco 平台與自動化 (Cisco Platforms)',
        '4.0 應用程式部署與安全性 (Application Deployment and Security)',
        '5.0 基礎架構與自動化 (Infrastructure and Automation)',
      ],
      iconName: 'code',
      isPopular: true,
    ),
  ];

  static ExamSubject getSubjectById(String id) {
    return allSubjects.firstWhere(
      (s) => s.id == id,
      orElse: () => allSubjects.first,
    );
  }
}
